/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/v1/auth/logout` — clears the session and tells the SPA where to send the browser.
         * @description It answers with JSON rather than a 302 on purpose: the SPA calls this with `fetch`, and a
         *     cross-origin redirect to Keycloak is unreadable to it. The browser navigation is the caller's.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/auth/me` — who is signed in. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_preferences"];
        put: operations["put_preferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_changes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/changes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_change"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/changes/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approve_change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/changes/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reject_change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/pipelines/{name}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["revisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/serviceaccounts/{name}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_keys"];
        put?: never;
        post: operations["create_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/serviceaccounts/{name}/keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revoke_key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/serviceaccounts/{name}/keys/{keyId}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotate_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/{plural}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/{plural}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_resource"];
        put: operations["replace"];
        post?: never;
        delete: operations["delete_resource"];
        options?: never;
        head?: never;
        patch: operations["patch"];
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sync_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/import-sdm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["import_sdm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/gitea": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["gitea_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for approving or rejecting a change proposal. */
        ApproveBody: {
            confirm?: string | null;
        };
        /**
         * @description What one Model Tools run rendered. Every artifact is optional: a version that does not
         *     render one omits it, and a source that does not compile yet answers with `errors` filled in
         *     and the artifacts absent. A half-written model is the normal state of an editor.
         */
        Artifacts: {
            context?: unknown;
            /** @description Compilation messages. Non-empty with no artifacts means the source does not compile. */
            errors?: string[];
            example?: unknown;
            /**
             * @description The generator version that produced these artifacts, so a preview and a committed
             *     artifact set can be compared (DM-19).
             */
            generatorVersion?: string | null;
            jsonSchema?: unknown;
            owl?: string | null;
            shacl?: string | null;
        };
        /** @description The `Change` resource describing a proposed configuration update. */
        Change: {
            apiVersion: string;
            kind: string;
            metadata: components["schemas"]["ChangeMeta"];
            status: components["schemas"]["ChangeStatus"];
        };
        /** @description Human author attributed on the change proposal. */
        ChangeAuthor: {
            email?: string | null;
            name: string;
        };
        /** @description Collection envelope for change proposals. */
        ChangeList: {
            apiVersion: string;
            items: components["schemas"]["ChangeProposal"][];
            kind: string;
        };
        /** @description Metadata identifying the change. */
        ChangeMeta: {
            /**
             * @description Identifier formatted as `chg-` plus eight lowercase hex characters derived
             *     from the merge request.
             */
            name: string;
            namespace: string;
        };
        /**
         * @description Lifecycle phase of a change.
         * @enum {string}
         */
        ChangePhase: "PendingApproval" | "Deploying" | "Merged" | "Applied" | "Rejected";
        /** @description A change proposal representing an open Git merge request. */
        ChangeProposal: {
            apiVersion: string;
            author: components["schemas"]["ChangeAuthor"];
            createdAt: string;
            kind: string;
            metadata: components["schemas"]["ChangeMeta"];
            planFields?: components["schemas"]["FieldChange"][] | null;
            status: components["schemas"]["ChangeStatus"];
            summary: components["schemas"]["ChangeSummary"];
        };
        /** @description Approval and reconciliation status of a change. */
        ChangeStatus: {
            lane: components["schemas"]["Lane"];
            mergeRequest?: string | null;
            phase: components["schemas"]["ChangePhase"];
            plan: components["schemas"]["PlanSummary"];
        };
        /** @description Human-readable proposal summary parameters derived from the plan diff. */
        ChangeSummary: {
            key: string;
            params: Record<string, never>;
        };
        /**
         * Condition
         * @description Status condition entry.
         */
        Condition: {
            /**
             * Format: date-time
             * @description Last transition timestamp.
             */
            lastTransitionTime?: string | null;
            /** @description Human-readable message. */
            message?: string | null;
            /** @description Machine-readable reason code. */
            reason?: string | null;
            /** @description Status value ("True", "False", "Unknown"). */
            status: string;
            /** @description Type of condition (e.g. Reconciled, Ready). */
            type: string;
        };
        /** @description Reviewer-facing validation and diff result returned on `?dryRun=All` (MF-13, R17). */
        DryRunResult: {
            lane: components["schemas"]["Lane"];
            plan: components["schemas"]["PlanDiff"];
            valid: boolean;
        };
        /**
         * @description A single leaf field modification in a plan diff.
         *
         *     Paths are dotted strings rooted at `metadata` or `spec` (e.g. `spec.audience`,
         *     `spec.representations[1]`, `metadata.labels.joinedcontext.com/domain`).
         *     Keys containing dots (such as reverse-DNS label names) are deliberately not escaped.
         */
        FieldChange: {
            from?: Record<string, never>;
            path: string;
            to?: Record<string, never>;
        };
        /** @description A LinkML source to compile. */
        GenerateRequest: {
            /** @description LinkML YAML, exactly as the editor holds it. */
            source: string;
        };
        Health: {
            name: string;
            status: string;
            version: string;
        };
        /** @description Who is signed in. Returned by `GET /api/v1/auth/me` and used by every protected route. */
        Identity: {
            email?: string | null;
            name?: string | null;
            /**
             * @description Keycloak realm roles from the ID token's `realm_access.roles` (CC-42). Empty when the
             *     token asserts none. Display and enablement only — the resource API and the forge enforce
             *     the same boundaries independently.
             */
            roles?: string[];
            /** @description Keycloak `sub`: stable, opaque, the only durable user key. */
            subject: string;
            username: string;
        };
        /** @description A model to import from the Smart Data Models catalogue. */
        ImportSdmRequest: {
            /**
             * @description Catalogue identifier, `dataModel.Environment/AirQualityObserved`. Never a URL: the
             *     allowlist that limits fetching to the Smart Data Models organisation lives in Model
             *     Tools (DM-10), and the Portal refuses anything a caller could steer.
             */
            model: string;
        };
        /**
         * @description One key as everyone else ever sees it: what an operator decides on, and nothing that opens
         *     a door.
         */
        KeyInfo: {
            createdAt: string;
            createdBy: string;
            credential: string;
            expiresAt?: string | null;
            keyId: string;
            lastUsedAt?: string | null;
            revokedAt?: string | null;
        };
        KeyList: {
            items: components["schemas"]["KeyInfo"][];
        };
        /**
         * @description Change risk classification lane (CC-63).
         * @enum {string}
         */
        Lane: "green" | "yellow" | "red";
        ListMeta: {
            continue?: string | null;
            remainingItemCount?: number | null;
        };
        /** @description The URL the browser must visit to finish an RP-initiated logout at Keycloak. */
        LogoutTarget: {
            /**
             * @description Absolute URL: Keycloak's `end_session_endpoint`, or the portal itself when no realm is
             *     configured.
             */
            endSessionUrl: string;
        };
        /** @description A minted key. The only place a raw token ever appears (PF-36). */
        MintedKey: {
            credential: string;
            expiresAt?: string | null;
            keyId: string;
            /** @description `jc_{keyId}_{secret}`, shown once and never recoverable (PF-37). */
            token: string;
        };
        /**
         * ObjectMeta
         * @description Metadata envelope attached to every platform resource (MF-02).
         */
        ObjectMeta: {
            /** @description Key-value annotations for provenance and ownership (MF-08). */
            annotations?: {
                [key: string]: string;
            };
            /** @description Human-readable multilingual description (PF-24). */
            description?: {
                [key: string]: string;
            } | null;
            /** @description Key-value labels for filtering (MF-10). */
            labels?: {
                [key: string]: string;
            };
            /** @description Resource name (DNS-1123 label). */
            name: string;
            /** @description Resource namespace ("org" or project slug). */
            namespace?: string | null;
            /** @description Human-readable multilingual title (PF-24). */
            title?: {
                [key: string]: string;
            } | null;
        };
        /**
         * Phase
         * @description Lifecycle phase enumeration.
         */
        Phase: "Draft" | "Pending" | "Deploying" | "Live" | "Error";
        PipelineMetrics: {
            /** Format: int64 */
            bufferDepth?: number | null;
            /** Format: int64 */
            errors?: number | null;
            /** Format: double */
            latencyP99Ms?: number | null;
            pipeline: string;
            /**
             * Format: int64
             * @description Cumulative since the runner started, exactly as it reports them: a rate is the view's
             *     job, history is Prometheus' job (OPS-16). An absent field is not zero, it is a counter
             *     this runner does not export.
             */
            received?: number | null;
            /** @description When the Portal read the runner, RFC 3339. The counters are as old as this instant. */
            scrapedAt: string;
            /** Format: int64 */
            sent?: number | null;
        };
        /** @description Summary and field-level changes between two resource revisions. */
        PlanDiff: {
            fields: components["schemas"]["FieldChange"][];
            summary: components["schemas"]["PlanSummary"];
        };
        /** @description Counts of planned resource mutations. */
        PlanSummary: {
            create?: number;
            delete?: number;
            update?: number;
        };
        Preferences: {
            /** @description Free JSON per dashboard name, the browser's own saved state. */
            dashboardLayouts?: Record<string, never>;
            /** @description The project the shell opens on. */
            defaultProject?: string | null;
            /** @description ISO 639-1 language code. */
            locale?: string | null;
            /** @description `light`, `dark` or `system`. */
            theme?: string | null;
        };
        /** @description RFC 7807 Problem Details representation. */
        ProblemDetails: {
            detail?: string | null;
            instance?: string | null;
            /** Format: int32 */
            status: number;
            title: string;
            type: string;
        };
        ResourceEnvelope: {
            apiVersion: string;
            kind: string;
            metadata: components["schemas"]["ObjectMeta"];
            spec?: Record<string, never>;
            status?: null | components["schemas"]["Status"];
        };
        ResourceList: {
            apiVersion: string;
            items: components["schemas"]["ResourceEnvelope"][];
            kind: string;
            metadata: components["schemas"]["ListMeta"];
        };
        Revision: {
            author: string;
            date: string;
            message: string;
            sha: string;
        };
        RevisionList: {
            items: components["schemas"]["Revision"][];
        };
        /**
         * @description The status the Portal API reports (MF-04). It is `jc_core::Status` plus `sourceUrl` and a phase
         *     that is always known; it stays a Portal type until jc-core carries `sourceUrl` too (docs API/01
         *     section 6 is the contract), then it becomes a re-export like its neighbours.
         */
        Status: {
            conditions?: components["schemas"]["Condition"][];
            observedRevision?: string | null;
            phase: components["schemas"]["Phase"];
            /**
             * @description Forge page of the file this manifest was read from, so a view can link "Source"
             *     without knowing where a kind lives in the repository. Computed, never read from Git.
             */
            sourceUrl?: string | null;
        };
        /**
         * @description Status of the background Git mirror synchronization.
         *
         *     Served to the browser, so it deliberately never carries a token,
         *     repository URL, or branch name.
         */
        SyncStatus: {
            lastError?: string | null;
            /** Format: int64 */
            lastSync?: number | null;
            manifests: number;
            revision?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared; navigate to endSessionUrl */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutTarget"];
                };
            };
            /** @description Missing or mismatched CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description No live session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's preferences, empty before the first save */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No preferences database configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    put_preferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Preferences"];
            };
        };
        responses: {
            /** @description Stored; the body is what is now saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preferences"];
                };
            };
            /** @description A field the Portal understands is invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing or mismatched CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No preferences database configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_changes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of change proposals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_change: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Change proposal ID (chg- + 8 hex digits) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Change proposal with plan diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeProposal"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Change proposal not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    approve_change: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Change proposal ID (chg- + 8 hex digits) */
                id: string;
            };
            cookie?: never;
        };
        /** @description Optional approval confirmation for red-lane changes */
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Change proposal approved and deploying */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request or missing red-lane confirmation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden (missing role or self-approval) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Change proposal not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    reject_change: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Change proposal ID (chg- + 8 hex digits) */
                id: string;
            };
            cookie?: never;
        };
        /** @description Optional reject payload */
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Change proposal rejected */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Change proposal not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: {
                /** @description yaml (default), json or zip */
                format?: string;
                /** @description Commit or branch; default branch head when absent */
                revision?: string;
                /** @description Comma-separated plurals to include */
                kinds?: string;
                /** @description Comma-separated resource names to include */
                names?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project's configuration at the revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown format or malformed revision */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such project or revision */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No repository configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Pipeline name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime counters of the stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineMetrics"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Pipeline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No runner configured, or it did not answer */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    revisions: {
        parameters: {
            query?: {
                /** @description 1…100, default 20 */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Commits touching the project, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionList"];
                };
            };
            /** @description limit out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No repository configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_keys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description ServiceAccount name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account's keys, metadata only */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such account, or none the caller may manage */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No key database configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    create_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description ServiceAccount name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description The minted key; the only answer that carries a token */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MintedKey"];
                };
            };
            /** @description No such api-key credential, or an expiry in the past */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such account, or none the caller may manage */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No key database configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    revoke_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description ServiceAccount name */
                name: string;
                /** @description Key to revoke */
                keyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked; the gateway refuses it on the next request */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such account or key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No key database configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    rotate_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description ServiceAccount name */
                name: string;
                /** @description Key to rotate */
                keyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description The successor key; the predecessor works until the overlap ends */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MintedKey"];
                };
            };
            /** @description An overlap window outside 0…168 hours */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such account or key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No key database configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description Label selector */
                labelSelector?: string;
                /** @description Field selector */
                fieldSelector?: string;
                /** @description Page limit */
                limit?: number;
                /** @description Pagination continue token */
                continue?: string;
                /** @description Historical revision */
                revision?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: {
                /** @description Set to 'All' for dry run */
                dryRun?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceEnvelope"];
            };
        };
        responses: {
            /** @description Dry run validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            /** @description Change proposal accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource envelope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    replace: {
        parameters: {
            query?: {
                /** @description Set to 'All' for dry run */
                dryRun?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceEnvelope"];
            };
        };
        responses: {
            /** @description Dry run validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            /** @description Change proposal accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    delete_resource: {
        parameters: {
            query?: {
                /** @description Set to 'All' for dry run */
                dryRun?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dry run validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            /** @description Change proposal accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict - blocking dependents */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    patch: {
        parameters: {
            query?: {
                /** @description Set to 'All' for dry run */
                dryRun?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        /** @description RFC 7386 merge patch, as JSON or as the YAML apply-patch document */
        requestBody: {
            content: {
                "application/merge-patch+json": string;
            };
        };
        responses: {
            /** @description Dry run validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            /** @description Change proposal accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_sync_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status of the background Git mirror synchronization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Compiled artifacts, or the messages of a source that does not compile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifacts"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Source larger than the payload limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No model tools service configured, or it did not answer */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    import_sdm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportSdmRequest"];
            };
        };
        responses: {
            /** @description Compiled artifacts of the catalogue model */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifacts"];
                };
            };
            /** @description Not a Smart Data Models catalogue identifier */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No model tools service configured, or it did not answer */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    gitea_webhook: {
        parameters: {
            query?: never;
            header: {
                /** @description HMAC-SHA256 signature of request body */
                "x-gitea-signature": string;
                /** @description Gitea event type (e.g. push, pull_request) */
                "x-gitea-event"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        /** @description Gitea webhook event payload */
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Webhook accepted and synchronization triggered */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Webhook accepted with no action needed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing or invalid signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Webhook secret not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
