/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * `POST /api/v1/auth/logout` — clears the session and tells the SPA where to send the browser.
         * @description It answers with JSON rather than a 302 on purpose: the SPA calls this with `fetch`, and a
         *     cross-origin redirect to Keycloak is unreadable to it. The browser navigation is the caller's.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** `GET /api/v1/auth/me` — who is signed in. */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_changes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/changes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_change"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/changes/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approve_change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/changes/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reject_change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/pipelines/{name}/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/{plural}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project}/{plural}/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_resource"];
        put: operations["replace"];
        post?: never;
        delete: operations["delete_resource"];
        options?: never;
        head?: never;
        patch: operations["patch"];
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_sync_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/gitea": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["gitea_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request body for approving or rejecting a change proposal. */
        ApproveBody: {
            confirm?: string | null;
        };
        /** @description The `Change` resource describing a proposed configuration update. */
        Change: {
            apiVersion: string;
            kind: string;
            metadata: components["schemas"]["ChangeMeta"];
            status: components["schemas"]["ChangeStatus"];
        };
        /** @description Human author attributed on the change proposal. */
        ChangeAuthor: {
            email?: string | null;
            name: string;
        };
        /** @description Collection envelope for change proposals. */
        ChangeList: {
            apiVersion: string;
            items: components["schemas"]["ChangeProposal"][];
            kind: string;
        };
        /** @description Metadata identifying the change. */
        ChangeMeta: {
            /**
             * @description Identifier formatted as `chg-` plus eight lowercase hex characters derived
             *     from the merge request.
             */
            name: string;
            namespace: string;
        };
        /**
         * @description Lifecycle phase of a change.
         * @enum {string}
         */
        ChangePhase: "PendingApproval" | "Deploying" | "Merged" | "Applied" | "Rejected";
        /** @description A change proposal representing an open Git merge request. */
        ChangeProposal: {
            apiVersion: string;
            author: components["schemas"]["ChangeAuthor"];
            createdAt: string;
            kind: string;
            metadata: components["schemas"]["ChangeMeta"];
            planFields?: components["schemas"]["FieldChange"][] | null;
            status: components["schemas"]["ChangeStatus"];
            summary: components["schemas"]["ChangeSummary"];
        };
        /** @description Approval and reconciliation status of a change. */
        ChangeStatus: {
            lane: components["schemas"]["Lane"];
            mergeRequest?: string | null;
            phase: components["schemas"]["ChangePhase"];
            plan: components["schemas"]["PlanSummary"];
        };
        /** @description Human-readable proposal summary parameters derived from the plan diff. */
        ChangeSummary: {
            key: string;
            params: Record<string, never>;
        };
        Condition: {
            lastTransitionTime: string;
            reason: string;
            status: string;
            type: string;
        };
        /** @description Reviewer-facing validation and diff result returned on `?dryRun=All` (MF-13, R17). */
        DryRunResult: {
            lane: components["schemas"]["Lane"];
            plan: components["schemas"]["PlanDiff"];
            valid: boolean;
        };
        /**
         * @description A single leaf field modification in a plan diff.
         *
         *     Paths are dotted strings rooted at `metadata` or `spec` (e.g. `spec.audience`,
         *     `spec.representations[1]`, `metadata.labels.joinedcontext.com/domain`).
         *     Keys containing dots (such as reverse-DNS label names) are deliberately not escaped.
         */
        FieldChange: {
            from?: Record<string, never>;
            path: string;
            to?: Record<string, never>;
        };
        Health: {
            name: string;
            status: string;
            version: string;
        };
        /** @description Who is signed in. Returned by `GET /api/v1/auth/me` and used by every protected route. */
        Identity: {
            email?: string | null;
            name?: string | null;
            /**
             * @description Keycloak realm roles from the ID token's `realm_access.roles` (CC-42). Empty when the
             *     token asserts none. Display and enablement only — the resource API and the forge enforce
             *     the same boundaries independently.
             */
            roles?: string[];
            /** @description Keycloak `sub`: stable, opaque, the only durable user key. */
            subject: string;
            username: string;
        };
        /**
         * @description Change risk classification lane (CC-63).
         * @enum {string}
         */
        Lane: "green" | "yellow" | "red";
        ListMeta: {
            continue?: string | null;
            remainingItemCount?: number | null;
        };
        /** @description The URL the browser must visit to finish an RP-initiated logout at Keycloak. */
        LogoutTarget: {
            /**
             * @description Absolute URL: Keycloak's `end_session_endpoint`, or the portal itself when no realm is
             *     configured.
             */
            endSessionUrl: string;
        };
        ObjectMeta: {
            annotations?: {
                [key: string]: string;
            };
            description?: {
                [key: string]: string;
            } | null;
            labels?: {
                [key: string]: string;
            };
            name: string;
            namespace?: string | null;
            title?: {
                [key: string]: string;
            } | null;
        };
        /** @enum {string} */
        Phase: "Draft" | "Pending" | "Deploying" | "Live" | "Error";
        PipelineMetrics: {
            /** Format: int64 */
            bufferDepth?: number | null;
            /** Format: int64 */
            errors?: number | null;
            /** Format: double */
            latencyP99Ms?: number | null;
            pipeline: string;
            /**
             * Format: int64
             * @description Cumulative since the runner started, exactly as it reports them: a rate is the view's
             *     job, history is Prometheus' job (OPS-16). An absent field is not zero, it is a counter
             *     this runner does not export.
             */
            received?: number | null;
            /** @description When the Portal read the runner, RFC 3339. The counters are as old as this instant. */
            scrapedAt: string;
            /** Format: int64 */
            sent?: number | null;
        };
        /** @description Summary and field-level changes between two resource revisions. */
        PlanDiff: {
            fields: components["schemas"]["FieldChange"][];
            summary: components["schemas"]["PlanSummary"];
        };
        /** @description Counts of planned resource mutations. */
        PlanSummary: {
            create?: number;
            delete?: number;
            update?: number;
        };
        /** @description RFC 7807 Problem Details representation. */
        ProblemDetails: {
            detail?: string | null;
            instance?: string | null;
            /** Format: int32 */
            status: number;
            title: string;
            type: string;
        };
        ResourceEnvelope: {
            apiVersion: string;
            kind: string;
            metadata: components["schemas"]["ObjectMeta"];
            spec?: Record<string, never>;
            status?: null | components["schemas"]["Status"];
        };
        ResourceList: {
            apiVersion: string;
            items: components["schemas"]["ResourceEnvelope"][];
            kind: string;
            metadata: components["schemas"]["ListMeta"];
        };
        Status: {
            conditions?: components["schemas"]["Condition"][];
            observedRevision?: string | null;
            phase: components["schemas"]["Phase"];
            /**
             * @description Forge page of the file this manifest was read from, so a view can link "Source"
             *     without knowing where a kind lives in the repository. Computed, never read from Git.
             */
            sourceUrl?: string | null;
        };
        /**
         * @description Status of the background Git mirror synchronization.
         *
         *     Served to the browser, so it deliberately never carries a token,
         *     repository URL, or branch name.
         */
        SyncStatus: {
            lastError?: string | null;
            /** Format: int64 */
            lastSync?: number | null;
            manifests: number;
            revision?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cleared; navigate to endSessionUrl */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutTarget"];
                };
            };
            /** @description Missing or mismatched CSRF token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description No live session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_changes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of change proposals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_change: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Change proposal ID (chg- + 8 hex digits) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Change proposal with plan diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeProposal"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Change proposal not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    approve_change: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Change proposal ID (chg- + 8 hex digits) */
                id: string;
            };
            cookie?: never;
        };
        /** @description Optional approval confirmation for red-lane changes */
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Change proposal approved and deploying */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request or missing red-lane confirmation */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden (missing role or self-approval) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Change proposal not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    reject_change: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Change proposal ID (chg- + 8 hex digits) */
                id: string;
            };
            cookie?: never;
        };
        /** @description Optional reject payload */
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["ApproveBody"];
            };
        };
        responses: {
            /** @description Change proposal rejected */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Change proposal not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Pipeline name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime counters of the stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineMetrics"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Pipeline not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No runner configured, or it did not answer */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                /** @description Label selector */
                labelSelector?: string;
                /** @description Field selector */
                fieldSelector?: string;
                /** @description Page limit */
                limit?: number;
                /** @description Pagination continue token */
                continue?: string;
                /** @description Historical revision */
                revision?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceList"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: {
                /** @description Set to 'All' for dry run */
                dryRun?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceEnvelope"];
            };
        };
        responses: {
            /** @description Dry run validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            /** @description Change proposal accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_resource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource envelope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceEnvelope"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    replace: {
        parameters: {
            query?: {
                /** @description Set to 'All' for dry run */
                dryRun?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResourceEnvelope"];
            };
        };
        responses: {
            /** @description Dry run validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            /** @description Change proposal accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    delete_resource: {
        parameters: {
            query?: {
                /** @description Set to 'All' for dry run */
                dryRun?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dry run validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            /** @description Change proposal accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict - blocking dependents */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    patch: {
        parameters: {
            query?: {
                /** @description Set to 'All' for dry run */
                dryRun?: string;
            };
            header?: never;
            path: {
                /** @description Project name */
                project: string;
                /** @description Resource kind plural */
                plural: string;
                /** @description Resource name */
                name: string;
            };
            cookie?: never;
        };
        /** @description RFC 7386 merge patch, as JSON or as the YAML apply-patch document */
        requestBody: {
            content: {
                "application/merge-patch+json": string;
            };
        };
        responses: {
            /** @description Dry run validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DryRunResult"];
                };
            };
            /** @description Change proposal accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unsupported media type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Git forge unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_sync_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status of the background Git mirror synchronization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    gitea_webhook: {
        parameters: {
            query?: never;
            header: {
                /** @description HMAC-SHA256 signature of request body */
                "x-gitea-signature": string;
                /** @description Gitea event type (e.g. push, pull_request) */
                "x-gitea-event"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        /** @description Gitea webhook event payload */
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Webhook accepted and synchronization triggered */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Webhook accepted with no action needed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Missing or invalid signature */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Webhook secret not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
