/** T-0220: what the model compiles to, while it is being written (DM-17, DM-20, DM-21). */
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { I18nextProvider } from "react-i18next";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import i18n from "../src/i18n";
import { LinkmlPreviewPanel, normalizedEntity, unmappedTerms } from "../src/pages/models/LinkmlPreviewPanel";
import { slotAffordance, slotDimension } from "../src/pages/models/linkml";
import type { LinkmlSlot } from "../src/pages/models/linkml";

const SOURCE = `id: https://banskabystrica.sk/models/air
name: air
classes:
  AirQualityObserved:
    slots: [pm10, dateObserved, location]
slots:
  pm10:
    range: float
  dateObserved:
    range: datetime
  location:
    annotations:
      ngsi_ld_kind: GeoProperty
`;

/** The documentation page Model Tools renders: one page for the whole model, seven columns,
 *  with the unit and the IRI the panel's old client-side rendering never had. */
const DOCS = `# air

<!-- generated by Model Tools, do not edit -->

- Rendered by: linkml-1.8.0

## Classes

### AirQualityObserved

| Attribute | NGSI-LD kind | Range | Required | Unit | IRI | Description |
|---|---|---|---|---|---|---|
| pm10 | Property | float | no | ug/m3 | https://banskabystrica.sk/terms/pm10 | Particulate matter. |
`;

const ARTIFACTS = {
  jsonSchema: {
    $schema: "http://json-schema.org/draft-07/schema#",
    title: "AirQualityObserved",
    type: "object",
    properties: { pm10: { type: "number", title: "pm10" } },
  },
  context: { "@context": { pm10: "https://banskabystrica.sk/terms/pm10" } },
  example: { id: "urn:ngsi-ld:AirQualityObserved:banskabystrica.sk:ovzdusie:st-1", pm10: 31.4 },
  docs: DOCS,
  generatorVersion: "linkml-1.8.0",
  errors: [],
};

function renderPanel(artifacts: unknown = ARTIFACTS, status = 200) {
  const fetchMock = vi.fn<(input: RequestInfo | URL) => Promise<Response>>(() =>
    Promise.resolve(
      new Response(JSON.stringify(artifacts), {
        status,
        headers: { "Content-Type": "application/json" },
      }),
    ),
  );
  vi.stubGlobal("fetch", fetchMock);
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(
    <QueryClientProvider client={client}>
      <I18nextProvider i18n={i18n}>
        <LinkmlPreviewPanel source={SOURCE} debounceMs={0} />
      </I18nextProvider>
    </QueryClientProvider>,
  );
  return { fetchMock, user: userEvent.setup() };
}

describe("LinkML preview panel", () => {
  beforeEach(async () => {
    await i18n.changeLanguage("en");
  });
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("compiles the source through the Portal and never through the browser", async () => {
    const { fetchMock } = renderPanel();

    await screen.findByText(/AirQualityObserved/);
    const request = fetchMock.mock.calls[0][0] as Request;
    expect(new URL(request.url).pathname).toBe("/api/v1/tools/generate");
    expect(request.method).toBe("POST");
    // Model Tools is the only component allowed to fetch a third-party schema (DM-10).
    for (const call of fetchMock.mock.calls) {
      expect(new URL((call[0] as Request).url).origin).toBe(window.location.origin);
    }
  });

  it("switches between the artifacts of one compilation", async () => {
    const { user } = renderPanel();
    await screen.findByText(/AirQualityObserved/);

    await user.click(screen.getByRole("tab", { name: "@context" }));
    expect(await screen.findByText(/banskabystrica.sk\/terms\/pm10/)).toBeInTheDocument();

    await user.click(screen.getByRole("tab", { name: "Example entity" }));
    expect(await screen.findByText(/urn:ngsi-ld:AirQualityObserved/)).toBeInTheDocument();

    await user.click(screen.getByRole("tab", { name: "Documentation" }));
    expect(await screen.findByText(/### AirQualityObserved/)).toBeInTheDocument();
  });

  /**
   * DM-32: two renderings of one artifact is how the editor and the repository drift apart.
   * The panel used to build this page itself, so what a reviewer approved was never what the
   * editor showed. The page comes from the artifact set now, and these are the parts of it
   * that the old client-side rendering could not have produced.
   */
  it("shows the documentation Model Tools rendered rather than a second rendering of it", async () => {
    const { user } = renderPanel();
    await screen.findByText(/AirQualityObserved/);

    await user.click(screen.getByRole("tab", { name: "Documentation" }));
    const page = await screen.findByText(/Rendered by: linkml-1.8.0/);

    expect(page).toHaveTextContent("ug/m3");
    expect(page).toHaveTextContent("https://banskabystrica.sk/terms/pm10");
    expect(page).toHaveTextContent("Particulate matter.");
    expect(page.textContent ?? "").not.toContain("| slot | range | kind | unit |");
  });

  it("says nothing was generated when the artifact set carries no documentation", async () => {
    const withoutDocs = { ...ARTIFACTS, docs: undefined };
    const { user } = renderPanel(withoutDocs);
    await screen.findByText(/AirQualityObserved/);

    await user.click(screen.getByRole("tab", { name: "Documentation" }));

    expect(await screen.findByText("Nothing compiled yet.")).toBeInTheDocument();
  });

  it("renders the form the JSON Schema produces, which is the form the Portal will show", async () => {
    const { user } = renderPanel();
    await screen.findByText(/AirQualityObserved/);

    await user.click(screen.getByRole("tab", { name: "Form" }));

    const field = await screen.findByLabelText("pm10");
    expect(field).toHaveValue(31.4);
    expect(field).toBeDisabled();
  });

  it("classifies every slot for the dashboards that will filter on it", async () => {
    const { user } = renderPanel();
    await screen.findByText(/AirQualityObserved/);

    await user.click(screen.getByRole("tab", { name: "Filters and layers" }));

    const rows = await screen.findAllByRole("row");
    const text = rows.map((row) => row.textContent ?? "");
    expect(text.some((row) => row.includes("pm10") && row.includes("range filter"))).toBe(true);
    expect(text.some((row) => row.includes("dateObserved") && row.includes("time filter"))).toBe(
      true,
    );
    expect(text.some((row) => row.includes("location") && row.includes("map layer"))).toBe(true);
  });

  it("names the terms an example carries that the generated context does not define", async () => {
    renderPanel({
      ...ARTIFACTS,
      example: { ...ARTIFACTS.example, temperature: 21 },
    });

    expect(await screen.findByRole("alert")).toHaveTextContent("temperature");
  });

  it("shows the compiler's own messages for a model that does not compile yet", async () => {
    renderPanel({ errors: ["slot 'pm10' has no range"] });

    expect(await screen.findByText("slot 'pm10' has no range")).toBeInTheDocument();
  });

  it("says the preview is unavailable rather than losing the source", async () => {
    renderPanel({ title: "Service Unavailable" }, 503);

    expect(
      await screen.findByText(/The preview service did not answer/),
    ).toBeInTheDocument();
  });

  it("counts only real terms as unmapped", () => {
    expect(
      unmappedTerms(
        { id: "urn:x", type: "Air", pm10: 1, "@context": [] },
        { "@context": { pm10: "https://x/pm10" } },
      ),
    ).toEqual([]);
    expect(unmappedTerms({ pm25: 1 }, { "@context": { pm10: "https://x/pm10" } })).toEqual([
      "pm25",
    ]);
    expect(unmappedTerms(undefined, undefined)).toEqual([]);
  });
});

/**
 * T-1092, DM-05: the generator's example is keyValues, which is not what a consumer parses. The
 * entity tab shows the payload an endpoint actually serves — each attribute wrapped in the
 * member its slot declares — so the author can tell a Property from a Relationship before the
 * space carries either.
 */
describe("the entity an endpoint would serve", () => {
  it("wraps each attribute in the member its slot declares", () => {
    const entity = normalizedEntity(
      {
        id: "urn:ngsi-ld:AirQualityObserved:hel.fi:ovzdusie:st-1",
        type: "AirQualityObserved",
        pm10: 31.4,
        station: "urn:ngsi-ld:Device:hel.fi:ovzdusie:d-1",
        label: { en: "Leppävaara" },
        band: "good",
        raw: { any: "shape" },
      },
      [
        // NGSI-LD `unitCode` takes the UN/CEFACT common code, which the unit carries in its
        // exact_mappings beside the UCUM symbol (DM-06).
        { name: "pm10", kind: "Property", unit: { ucum_code: "ug/m3", exact_mappings: ["ucefact:GQ"] } },
        { name: "station", kind: "Relationship" },
        { name: "label", kind: "LanguageProperty" },
        { name: "band", kind: "VocabProperty" },
        { name: "raw", kind: "JsonProperty" },
      ] as never,
    );

    // The keywords stay as they are: an id is not an attribute.
    expect(entity?.id).toBe("urn:ngsi-ld:AirQualityObserved:hel.fi:ovzdusie:st-1");
    expect(entity?.type).toBe("AirQualityObserved");
    // Each native type carries its own member (the owner's target architecture, change 2).
    expect(entity?.pm10).toEqual({ type: "Property", value: 31.4, unitCode: "GQ" });
    expect(entity?.station).toEqual({
      type: "Relationship",
      object: "urn:ngsi-ld:Device:hel.fi:ovzdusie:d-1",
    });
    expect(entity?.label).toEqual({ type: "LanguageProperty", languageMap: { en: "Leppävaara" } });
    expect(entity?.band).toEqual({ type: "VocabProperty", vocab: "good" });
    expect(entity?.raw).toEqual({ type: "JsonProperty", json: { any: "shape" } });
  });

  it("treats a slot the model does not declare as a plain Property, and answers nothing for no example", () => {
    expect(normalizedEntity({ unknown: 1 }, [])).toEqual({
      unknown: { type: "Property", value: 1 },
    });
    expect(normalizedEntity(undefined, [])).toBeUndefined();
  });
});

/**
 * T-1113, DM-20: the classification a dashboard reads. "numeric ranges → range filter and
 * sizeBy; enums → select filter and colorBy; datetime/date → temporal; GeoProperty → map layer
 * geometry; Relationships → link picker." The select case could never be reached while the
 * classification judged a slot without the model's enum names beside it.
 */
describe("what a dashboard may do with a slot", () => {
  const enums = ["QualityBand"];

  it("classifies every case DM-20 names, the enum included", () => {
    const of = (slot: Partial<LinkmlSlot>) =>
      slotAffordance({ name: "s", kind: "Property", ...slot } as LinkmlSlot, enums);

    expect(of({ kind: "GeoProperty" })).toBe("geometry");
    expect(of({ kind: "Relationship" })).toBe("link");
    expect(of({ range: "QualityBand" })).toBe("select");
    expect(of({ range: "datetime" })).toBe("temporal");
    expect(of({ range: "date" })).toBe("temporal");
    expect(of({ range: "float" })).toBe("range");
    expect(of({ range: "integer" })).toBe("range");
    expect(of({ range: "string" })).toBe("text");
    // Without the model's enums beside it, an enum range reads as text: the case the panel
    // could not show before.
    expect(slotAffordance({ name: "s", kind: "Property", range: "QualityBand" } as LinkmlSlot)).toBe(
      "text",
    );
  });

  /**
   * T-1175, Architecture/11 §1.1: the four kinds beyond Property and Relationship say what the
   * value *is*, and the range only says what one element of it is. While the classification
   * read the range alone, a language map and an opaque document both arrived as `text` and the
   * editor promised a text filter over a JSON object.
   */
  it("reads the kind before the range, so a map and a document are not text", () => {
    const of = (slot: Partial<LinkmlSlot>) =>
      slotAffordance({ name: "s", kind: "Property", ...slot } as LinkmlSlot, enums);

    expect(of({ kind: "LanguageProperty", range: "string" })).toBe("language-map");
    expect(of({ kind: "JsonProperty", range: "string" })).toBe("code");
    expect(of({ kind: "VocabProperty", range: "QualityBand" })).toBe("select");
    // A vocabulary whose enum the model has not declared is still a pick, not free text.
    expect(of({ kind: "VocabProperty", range: "Pollutant" })).toBe("select");
    // A list of terms picks from them; a list of anything else has no set to pick from.
    expect(of({ kind: "ListProperty", range: "QualityBand" })).toBe("multi-select");
    expect(of({ kind: "ListProperty", range: "float" })).toBe("text");
  });

  it("names the dimension a dashboard sizes or colours by, and nothing for the rest", () => {
    expect(slotDimension("range")).toBe("sizeBy");
    expect(slotDimension("select")).toBe("colorBy");
    for (const affordance of [
      "temporal",
      "geometry",
      "link",
      "text",
      // A multi-select has no one value per entity to colour by, and a map and a document
      // have none at all.
      "multi-select",
      "language-map",
      "code",
    ] as const) {
      expect(slotDimension(affordance)).toBeUndefined();
    }
  });
});

/**
 * T-1096, DM-21: a `@context` is one object, or an array of objects and URLs of more. The panel
 * names a term the context does not define, so it must read every shape — and must stay silent
 * where it cannot be sure, because a false "unmapped" about a model is worse than no warning.
 */
describe("the terms a context does not define", () => {
  const example = { id: "urn:ngsi-ld:X:a:b:1", type: "X", pm10: 1, station: "s" };

  it("reads the terms of every object of an array context", () => {
    expect(
      unmappedTerms(example, {
        "@context": [{ pm10: "bb:pm10" }, { station: "bb:station" }],
      }),
    ).toEqual([]);
    expect(unmappedTerms(example, { "@context": [{ pm10: "bb:pm10" }] })).toEqual(["station"]);
  });

  it("says nothing when a vocabulary resolves every term", () => {
    expect(unmappedTerms(example, { "@context": { "@vocab": "https://bb.sk/terms/" } })).toEqual([]);
    expect(
      unmappedTerms(example, { "@context": [{ pm10: "bb:pm10" }, { "@vocab": "https://bb.sk/" }] }),
    ).toEqual([]);
  });

  it("says nothing when a context it cannot fetch might define the rest", () => {
    expect(
      unmappedTerms(example, {
        "@context": ["https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld"],
      }),
      "a remote context may define them; a false alarm is worse than silence",
    ).toEqual([]);
    expect(
      unmappedTerms(example, {
        "@context": ["https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context.jsonld", { pm10: "bb:pm10" }],
      }),
    ).toEqual([]);
  });

  it("still names a term nothing defines", () => {
    expect(unmappedTerms(example, { "@context": { pm10: "bb:pm10" } })).toEqual(["station"]);
  });
});
